version: "3.9"

services:
  db:
    image: postgres:16
    container_name: kadr-db
    environment:
      POSTGRES_DB: kadr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kadr-appp
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/kadr
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  db-data:
